version: '3.6'

services:
  postgres_jimmy:
    container_name: jimmy_postgres_container
    image: postgres:12.3
    environment:
      POSTGRES_DB: ${JIMMY_FT_RDS_DB_NAME:-jimmy_ft}
      POSTGRES_USER: ${JIMMY_FT_RDS_USERNAME:-jimmy_ft}
      POSTGRES_PASSWORD: ${JIMMY_FT_RDS_PASSWORD:-testpwd1}
      PGDATA: /data/postgres_jimmy
    volumes:
      - postgres_jimmy:/data/postgres_jimmy
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_jimmy:
